---
- name: rc.local配布
  template:
    src: rc.local.j2
    dest: /etc/rc.local
    owner: root
    group: root
    mode: '777'

- name: ファイルディスクリプタとプロセスの上限値の設定
# limits.conf api01だけ設定値が一部異なっている
  copy:
    src: limits.conf
    dest: /etc/security/limits.conf
    owner: root
    group: root
    mode: '0644'

- name: sysctl.confの設定
  copy:
    src: sysctl.conf
    dest: /etc/
    owner: root
    group: root
    mode: '0644'

- name: lsyncdのインストール
  yum:
    name: lsyncd
    disablerepo: epel

- name: lsyncdの権限変更
  file:
    path: /etc/sysconfig/lsyncd
    mode: '0755'

- name: lsyncd用のログディレクトリ作成
  file:
    state: directory
    path: /var/log/lsyncd/

- name: lsyncd用のディレクトリ作成
  file:
    state: directory
    path: '{ item }'
  with_items:
    - { path: /var/app/acq, owner: tomcat, group: tomcat, mode: 0755 }
    - { path: /var/app/fs, owner: tomcat, group: tomcat, mode: 0755 }
    - { path: /var/app/trdads, owner: tomcat, group: tomcat, mode: 0755 }

- name: 設定ファイルのコピー
# templateにする。target=が自ipに
  template:
    src: lsyncd.conf.j2
    dest: /etc/lsyncd.conf
    owner: root
    group: root
    mode: '0644'

- name: 192.168.134系のipを代入
  debug:
    var: item
  register: mount_ip
  when: item | match("192.168.134.*")
  with_items: '{{ ansible_all_ipv4_addresses }}'

- name: nasのマウントに必要なディレクトリを作成
# nas06側の/nas/app配下にIPアドレスのディレクトリを手動で別途作成すること
  file:
    state: directory
    path: '{{ items }}'
  with_items:
    - { path: /nas/backup, owner: root, group: root, mode: 0777 }
    - { path: /nas/cvpath, owner: root, group: root, mode: 0777 }
    - { path: /nas/app, owner: nobody, group: nobody, mode: 0777 }

- name: fstabのコピー
# 設定内容は一緒だけどuuidが使われている、、築城だけでいいか
  lineinfile:
    path: /etc/fstab
    line: '{{ item }}'
  with_items:
    - "192.168.134.205:/backup    /nas/backup      nfs    rsize=8192,wsize=8192,hard,intr,noatime 0 0"
    - "192.168.134.205:/cvpath    /nas/cvpath      nfs    rsize=8192,wsize=8192,hard,intr,noatime 0 0"
    - "192.168.134.205:/nas/app　 /nas/app         nfs    rsize=8192,wsize=8192,hard,intr 0 0"

- name: マウント
  mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    state: mounted
    fstype: nfs
    opts: "{{ item.opts }}"
  with_items:
    - { src: "192.168.134.205:/backup", path: /nas/backup, opts: "rsize=8192,wsize=8192,hard,intr,noatime" }
    - { src: "192.168.134.205:/cvpath", path: /nas/cvpath, opts: "rsize=8192,wsize=8192,hard,intr,noatime" }
    - { src: "192.168.134.205:/nas/app", path: /nas/app, opts: "rsize=8192,wsize=8192,hard,intr" }

- name: lsyncdの起動し、自動起動も設定
  service:
    name: lsyncd
    state: started
    enabled: yes

- name: logroteの設定
  copy:
    src: lsyncd_logrote
    dest: /etc/logrotate.d/lsyncd
    mode: '0644'

- name: beacon.gifファイルを配置
  copy:
    src: beacon.gif
    dest: /usr/local/nginx/html/
    mode: '0644'

- name: cronの設定ファイルを配置
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
  with_items: '{{ cron }}'

- name: ログローテの設定
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
  with_items: '{{ logrote }}'

- name: /root/temp/のディレクトリを配置
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
  with_items: '{{ root_temp }}'
