---
- name: install parted
  yum:
    name: parted

- name: partitioning
  shell: /sbin/parted --script /dev/sdb 'mklabel gpt' && /sbin/parted --script /dev/sdb "mkpart sdb xfs 0% 100%"

- name: create filesystem
  filesystem:
    fstype: xfs
    dev: /dev/sdb1
  asycn: 14400
  poll: 60

- name: get UUID
  shell: blkid /dev/sdb1 | grep -o 'UUID=.*' | sed -e 's/UUID="//g' -e 's/".*//'
  register: uuid

- name: create dir
  file:
    path: /ssd
    state: directory
    mode: '0755'

- name: mount up device by UUID
  mount:
    path: /ssd
    src: UUID={{ uuid.stdout }}
    fstype: xfs
    dump: '1'
    passno: '2'
    opts: defaults,noatime,nobarrier
    state: present
