---
- name: 本日の日付を取得
  local_action: command date +"%Y%m%d"
  register: date

- name: sync-dsp証明書格納用ディレクトリを作成
  file:
    path: /etc/nginx/conf.d/sync-dsp.ad-m.asia
    state: directory
    mode: '0755'

- name: バックアップを作成
  command: "cp {{ item }} {{ item }}.{{ date.stdout }}"
  with_items:
    - '{{ dsp_crt_path }}'
    - '{{ dsp_key_path }}'
  ignore_errors: true

- name: ファイルをコピー
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0755
  with_items:
    - { src: '{{ update_dsp_crt }}', dest: '{{ dsp_crt_path }}' }
    - { src: '{{ update_dsp_key }}', dest: '{{ dsp_key_path }}' }

- name: 鍵ファイルの権限変更
  file:
    path: '{{ dsp_key_path }}'
    mode: 0644

#debug
- name: ssl証明書の確認
  command: openssl x509 -text -noout -in '{{ dsp_crt_path }}'
  register: check_sync-dsp.ad-m.asia_crt

- name: 鍵の一致のテスト(sync-dsp.ad-m.asia.crt)
  shell: openssl x509 -noout -modulus -in '{{ dsp_crt_path }}' | openssl md5
  register: match_sync-dsp.ad-m.asia_crt

- name: 鍵の一致のテスト(sync-dsp.ad-m.asia.key)
  shell: openssl rsa -noout -modulus -in '{{ dsp_key_path }}' | openssl md5
  register: match_sync-dsp.ad-m.asia_key

- name: nginx設定ファイルの文法チェック
  command: /usr/local/nginx/sbin/nginx -t -c /etc/nginx/nginx.conf
  register: configtest
  ignore_errors: true

- name: debug
  debug: var=check_sync-dsp.ad-m.asia_crt.stdout_lines

- name: debug
  debug: var=match_sync-dsp.ad-m.asia_crt.stdout_lines

- name: debug
  debug: var=match_sync-dsp.ad-m.asia_key.stdout_lines

- name: debug
  debug: var=configtest.stderr_lines
