---
- name: authorized_keysをコピー(jenkinsとの疎通のため)
  copy:
    src: authorized_keys
    dest: /home/tomcat/.ssh/

- name: irqbalanceインストール
  yum:
    name: irqbalance
    state: latest

- name: irqbalance起動
  command: /etc/init.d/irqbalance start

- name: rc.localの編集
  lineinfile:
    dest=/etc/rc.local
    line={{ item }}
  with_items:
    - 'echo "ffffffff" > /sys/class/net/em2/queues/tx-0/xps_cpus'
    - 'echo "ffffffff" > /sys/class/net/em2/queues/rx-0/rps_cpus'
    - 'echo "ffffffff" > /sys/class/net/em2/queues/rx-1/rps_cpus'
    - 'echo "ffffffff" > /sys/class/net/em2/queues/rx-2/rps_cpus'
    - 'echo "ffffffff" > /sys/class/net/em2/queues/rx-3/rps_cpus'
    - 'echo "ffffffff" > /sys/class/net/em2/queues/rx-4/rps_cpus'
    - 'echo 4096 > /sys/class/net/em2/queues/rx-0/rps_flow_cnt'
    - 'echo 4096 > /sys/class/net/em2/queues/rx-1/rps_flow_cnt'
    - 'echo 4096 > /sys/class/net/em2/queues/rx-2/rps_flow_cnt'
    - 'echo 4096 > /sys/class/net/em2/queues/rx-3/rps_flow_cnt'
    - 'echo 4096 > /sys/class/net/em2/queues/rx-4/rps_flow_cnt'
    - 'echo 32768 > /proc/sys/net/core/rps_sock_flow_entries'

- name: 必要なディレクトリの作成
  file:
    state: directory
    path: '{{ item }}'
    owner: tomcat
    group: tomcat
    mode: 0755
  with_items:
    - /var/app/test/unitag/logs
    - /var/app/optout/logs
    - /var/app/unitag/logs
    - /var/app/fs/dmp/bin/backup
    - /var/app/fs/dsp/config

- name: fsdkvs用フォルダを作成
  file:
    state: directory
    path: /etc/fsdkvs/conf
    mode: 0755

- name: fsdkvs/confの権限設定
  file: 
    path: /etc/fsdkvs/conf
    owner: tomcat
    group: tomcat
    
- name: fsdkvsのconfファイルを配置
  copy:
    src: fsdkvs_conf/{{ item.src }}
    dest: /etc/fsdkvs/conf
    mode: ' {{ item.mode }}'
    owner: tomcat
    group: tomcat
  with_items:
    - { src: client-site.properties, mode: 0640 }
    - { src: manager-site.properties, mode: 0644 }

- name: fs/dsp/config用のymlファイルをコピー
  copy:
    src: fs_dsp_config/{{ item }}
    dest: /var/app/fs/dsp/config/
    owner: tomcat
    group: tomcat
    mode: 0644
  with_items:
    - env.yml
    - search_engine.yml

- name: tomcat/bin/のスクリプトファイル配置
  copy:
    src: tomcat_bin/{{ item }}
    dest: /usr/local/tomcat/bin/
    owner: tomcat
    group: tomcat
    mode: 0755
  with_items:
    - startup.sh
    - shutdown.sh
    - setenv.sh
    - catalina.sh

- name: server.xmlの配置
  copy:
    src: server.xml
    dest:  /usr/local/tomcat/conf/
    owner: tomcat
    group: tomcat
    mode: 0600

- name: webapps/sync-tapi.admatrix.jpディレクトリを作成
  file:
    state: directory
    path: /usr/local/tomcat/webapps/sync-tapi.admatrix.jp/ROOT/
    owner: tomcat
    group: tomcat
    mode: 0755

- name: sync用のjspファイルを配置
  copy:
    src: sync.jsp
    dest:  /usr/local/tomcat/webapps/sync-tapi.admatrix.jp/ROOT/
    owner: tomcat
    group: tomcat
    mode: 0644

- name: warファイルを配置
  copy:
    src: dsp.war
    dest:  /usr/local/tomcat/webapps/
    owner: tomcat
    group: tomcat
    mode: 0644

- name: tomcatの再起動
  become: tomcat
  shell: /usr/local/tomcat/bin/startup.sh

# cron
- name: create the directory
  file:
    path: /root/temp
    mode: '0755'
    state: directory

- name: log転送スクリプトを配置
  copy:
    src: '{{ item }}'
    dest: /root/temp/
    mode: '0755'
  with_items:
    - cron/backupLogsToRemoteServer.sh
    - cron/setBackupVariables.sh
    - cron/trdads_backup_logs

- name: cronスクリプトを配置
  copy:
    src: cron/trdads_backup_logs
    dest: /etc/cron.daily/
    mode: '0755'

- name: copy limits.conf
  copy:
    src: limits.conf
    dest: /etc/security/
    mode: '0644' 
