---
- name: 本日の日付を取得
  local_action: command date +"%Y%m%d"
  register: date

- name: バックアップを作成
  command: "cp {{ item }} {{ item }}.{{ date.stdout }}"
  with_items:
    - '{{ crt_path }}'
    - '{{ key_path }}'

- name: ファイルをコピー
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0755
  with_items:
    - { src: '{{ update_crt }}', dest: '{{ crt_path }}' }
    - { src: '{{ update_key }}', dest: '{{ key_path }}' }

- name: 鍵ファイルの権限変更
  file:
    path: '{{ key_path }}'
    mode: 0644

#debug
- name: ssl証明書の確認
  command: openssl x509 -text -noout -in '{{ crt_path }}'
  register: check_admatrix_crt

- name: 鍵の一致のテスト(admatrix.crt)
  shell: openssl x509 -noout -modulus -in '{{ crt_path }}' | openssl md5
  register: match_admatrix_crt

- name: 鍵の一致のテスト(admatrix.key)
  shell: openssl rsa -noout -modulus -in '{{ key_path }}' | openssl md5
  register: match_admatrix_key

- name: apache設定ファイルの文法チェック
  command: /etc/init.d/httpd configtest
  register: configtest

- name: debug
  debug: var=check_admatrix_crt.stdout_lines

- name: debug
  debug: var=match_admatrix_crt.stdout_lines

- name: debug
  debug: var=match_admatrix_key.stdout_lines

- name: debug
  debug: var=configtest.stderr_lines

- name: httpdのconfigtest
  debug: var=configtest.stderr
