---
- name: ディレクトリの情報を取得
  find:
    paths: "/data"
    file_type: directory
    patterns: "disk*"
  register: disk_dir

- name: dfsディレクトリの作成
  file:
    path: "{{ item.path }}/dfs/dn"
    state: directory
  with_items: "{{ disk_dir.files }}"

- name: tmpディレクトリの作成
  file:
    path: "{{ item.path }}/tmp"
    state: directory
  with_items: "{{ disk_dir.files }}"

- name: mr必要なディレクトリの作成
  file:
    path: "{{ item.path }}/mapred/local"
    state: directory
  with_items: "{{ disk_dir.files }}"

- name: yarn必要なディレクトリの作成
  file:
    path: "{{ item.path }}/yarn/local"
    state: directory
  with_items: "{{ disk_dir.files }}"

- name: /data/disk*/dfs系のユーザ設定
  file:
    path: "{{ item.path }}/dfs"
    state: directory
    owner: hdfs
    group: hadoop
    recurse: yes
  with_items: "{{ disk_dir.files }}"

- name: /data/disk*/tmp系のユーザ設定
  file:
    path: "{{ item.path }}/tmp"
    state: directory
    owner: hdfs
    group: hadoop
    recurse: yes
  with_items: "{{ disk_dir.files }}"

- name: mapred系のユーザ設定
  file:
    path: "{{ item.path }}/mapred"
    state: directory
    owner: mapred
    group: hadoop
    recurse: yes
  with_items: "{{ disk_dir.files }}"

- name: disk*の権限設定
  file:
    path: "{{ item.path }}"
    mode: 0755
  with_items: "{{ disk_dir.files }}"

- name: hdfs-sockets/作成、権限設定
  file:
    path: /var/run/hdfs-sockets
    state: directory
    owner: hdfs
    group: hadoop
    mode: 0755

- name: yarnディレクトリの作成、権限設定
  file:
    path: "{{ item.path }}/yarn/local"
    state: directory
    owner: yarn
    group: yarn
    mode: 0755
  with_items: "{{ disk_dir.files }}"

- name: yarn.hadoopのディレクトリ作成、権限設定
  file:
    path: "{{ item }}"
    state: directory
    owner: yarn
    group: hadoop
    mode: 0755
  with_items:
      - /usr/lib/hadopp-yarn/logs
      - /data/yarn-nm-recovery

