---
- name: CDHのyum repositoryの設定(共通)
  include: ../../common_build/tasks/CDH_yum_conf.yml

- name: glibc-commonのバージョンを要求されるものに合わせる
  command: yum -y downgrade glibc glibc-common glibc-devel glibc-headers

- name: dnミドルウェアをインストール
  yum: name={{item}} state=present disablerepo=fullspeed enablerepo=cloudera-cdh5
  with_items:
    - hadoop-hdfs-datanode
    - hadoop-lzo
    - hadoop-yarn-nodemanager
    - hadoop-mapreduce
#ここでエラーが出たらglibc-common他をdowngradeする必要あるかも

- name: シンボリックリンクの調整
  include: ../../common_build/tasks/create_link_slf4j-log4j12jar.yml

- name: 自動起動の設定をoffにしておく
  service: name={{ item }} enabled=off
  with_items:
    - hadoop-hdfs-datanode
    - hadoop-yarn-nodemanager

- name: 必要なユーザの作成
  include: ../../common_build/tasks/create_user.yml

- name: confファイルの準備
  include: ../../common_build/tasks/create_conf.yml

- name: 設定ファイルを配布(共通)
  include: ../../common_build/tasks/give_conf_files.yml

- name: 設定ファイル配布(dn)
  copy:
    src: "{{ item }}"
    dest: /etc/hadoop/conf/
    owner: root
    group: root
    mode: 0644
  with_items: '{{ dn_files }}'

# 以下ディレクトリと権限設定
- name: ディレクトリの作成(dn)
  include: create_directory.yml

- name: add nn to a hosts
  copy:
    src: ../../admatrixDSP_infra_configfiles/hosts
    dest: /etc/hosts
    backup: yes

