---
- name: cronの設定ファイルを配置
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
  with_items: '{{ cron }}'

- name: ログローテの設定
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
  with_items: '{{ logrote }}'

- name: /root/temp/のディレクトリを配置
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
  with_items: '{{ root_temp }}'
