---
- name: install keepalived
  become: yes
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - keepalived
    - ipvsadm

- name: set keepalived.conf
  become: yes
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    backup: yes
