---
- name: control onpremise server
  hosts: add
  become: true
  roles:
    - ../common_build/roles/common
    - ../common_build/roles/java
  tasks:
    - name: sysctl.confの値を一部変更
      sysctl:
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        state: present
      with_items:
        - { name: net.ipv4.tcp_synack_retries, value: '3' }
        - { name: net.netfilter.nf_conntrack_max, value: '500000' }
        - { name: net.nf_conntrack_max, value: '500000' }
        - { name: net.core.somaxconn, value: '2048' }
        - { name: net.ipv4.ip_local_port_range, value: '32768 65000' }
    - name: sysctl.confの値を一部削除
      sysctl:
        name: '{{ item.name }}'
        state: absent
      with_items:
        - { name: net.core.rmem_max }
        - { name: net.core.wmem_max }
        - { name: net.ipv4.tcp_rmem }
        - { name: net.ipv4.tcp_wmem }
    - name: nginx用ディレクトリを作成しておく
      file:
        state: directory
        path: /etc/nginx/conf.d/sync-dsp.ad-m.asia
        mode: '0755'

- name: control onpremise server
  hosts: add
  become: true
  vars_files:
    - vars/nginx.yml
    - vars/mount.yml
    - vars/ssl_sync-dsp.ad-m.asia.yml
    - vars/ssl_sync-dmp.sashare.com.yml
  roles:
    - ../common_build/roles/nginx
    - ../common_build/roles/ssl_admatrix.jp
    - ssl_sync-dmp.sashare.com
    - ssl_sync-dsp.ad-m.asia
    - ../common_build/roles/tomcat
    - tapi
    - ../common_build/roles/mount
