---
- name: hdfsの起動(dn)
  service:
    name: hadoop-hdfs-datanode
    state: started

- name: mapreduceの起動(dn)
  service:
    name: hadoop-0.20-mapreduce-tasktracker
    state: started

# 15.MapReduceの動作確認 ディレクトリ作成、データアップ、起動
