---
#使わないインターフェースが立ち上がらないようにするため
- hosts: target #kdt
  become: true
  tasks:
    - name: check existence of file
      stat:
        path: /etc/sysconfig/network-scripts/ifcfg-em1
      register: file

    - name: edit network interface
      lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-em1
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
      with_items:
        - { regexp: '^BOOTPROTO=', line: 'BOOTPROTO="none"' }
        - { regexp: '^IPV6INIT=', line: 'IPV6INIT="none"' }
        - { regexp: '^ONBOOT=', line: 'ONBOOT="none"' }
      when: file.stat.exists

    - name: network restart
      service:
        name: network
        state: restarted

    - name: ifconfig
      command: ifconfig
      register: ifconfig

    - name: debug
      debug: var=ifconfig.stdout_lines

