---
- name: copy script
  copy:
    src: cron/backup_cbatch.sh
    dest: /var/app/fs/dsp/bin/backup_cbatch.sh
    mode: 0755

- name: set crontab
  cron:
    name: backup_cbatch.sh
    minute: 0
    hour: 2
    job: "/var/app/fs/dsp/bin/backup_cbatch.sh >/dev/null 2>&1"

- name: install neccesary midleware
  yum:
    name: '{{ item }}'
    enablerepo: fullspeed
  with_items:
    - srvadmin-tomcat
