---
- hosts: add
  become: true
  roles:
    - ../common_build/roles/common
    - ../common_build/roles/java
    - activemq
        - apache_tomcat
    - ../common_build/roles/hadoop_client
    - batch02
    - ../common_build/roles/mount
