---
- hosts: add
  become: true
  vars:
    create_host: batch01
    mysql_password: sysdev
  vars_files:
    - vars/mount_for_batch01.yml
  roles:
    - ../common_build/roles/common
    - batch01 #sysctlの修正、gwの修正、
    - ../common_build/roles/java
    - mysql
    - ../common_build/roles/hadoop_client
    - sqoop
    - azkaban
    - ../common_build/roles/mount

# azkabanのエラーメール設定を行う
