---
- name: set repository
  copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb-org-3.6.repo
    mode: '0644'

- name: install mongo's packages
  yum:
    name: '{{ item }}'
    enablerepo: mongodb-org-3.6
  with_items:
    - mongodb-org

- name: set config file
  copy:
    src: mongod.conf
    dest: /etc/
    mode: '0644'
  tags: test

- name: create directory
  file:
    path: /data/mongo
    state: directory
    mode: '0777'

- name: set authority
  file:
    path: /data
    state: directory
    mode: '0755'

## セキュリティ設定
- name: create directory
  file:
    path: /usr/local/mongodb/conf
    state: directory

- name: set keyfiles
  copy:
    src: mongodb-keyfile
    owner: mongod
    group: mongod
    mode: '0600'

# transparent-hugepages設定
# https://docs.mongodb.com/manual/tutorial/transparent-huge-pages/#configure-thp-tuned
- name: copy disable-transparent-hugepages
  copy:
    src: disable-transparent-hugepages
    dest: /etc/init.d/
    mode: '0755'

- name: run it on boot
  service:
    name: disable-transparent-hugepages
    enalbed: yes

## 90-nproc.confの編集
- name: add lines
  lineinfile:
    path: /etc/security/limits.d/90-nproc.conf
    line: '{{ item }}'
  with_items:
    - '*          soft    nofile    64000'
    - '*          hard    nofile    64000'

##
- name: install modules
  yum:
    name: '{{ item }}'
  with_items:
    - pymongo
    - numactl

- name: start mongo
  service:
    name: mongod
    state: started

- name: create root user
  mongodb_user:
    database: admin
    name: root
    password: sysdev
    state: present
    roles: root

- name: create application user
  mongodb_user:
    database: admin
    name: dsp
    password: 'y8WFycQP'
    state: present
    roles: readWriteAnyDatabase

- name: stop mongod
  service:
    name: mongod
    state: stopped

- name: comment out config file
  lineinfile:
    path: /etc/mongod.conf
    regexp: '^#  authorization: enabled'
    line: '  authorization: enabled'

- name: set config file for replication
  lineinfile:
    path: /etc/mongod.conf
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: '^#replication:', line: 'replication:' }
    - { regexp: '^#  replSetName: nfsmongo', line: '  replSetName: nfsmongo' }

##
- name: edit sysctl.conf
  sysctl:
    name: vm.zone_reclaim_mode
    value: '0'
    state: present

##
- name: start mongodb
  command: numactl --interleave=all mongod -f /etc/mongod.conf
