---
- name: Hadoop用カーネルパラメータを設定 #デフォルトでreloadしてくれる
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - name: kernel.panic_on_oops
      value: 1
    - name: kernel.panic
      value: panic
    - name: kernel.softlockup_panic
      value: 1
    - name: kernel.hung_task_panic
      value: 1
    - name: net.core.netdev_max_backlog
      value: 4096
    - name: net.core.somaxconn
      value: 1024
    - name: net.core.rmem_max
      value: 16777216
    - name: net.core.wmem_max
      value: 16777216
    - name: net.ipv4.tcp_rmem
      value: 4096 87380 16777216
    - name: net.ipv4.tcp_wmem
      value: 4096 65536 16777216
    - name: net.ipv4.tcp_max_syn_backlog
      value: 8192
    - name: net.ipv6.conf.all.disable_ipv6
      value: 1
    - name: net.ipv6.conf.lo.disable_ipv6
      value: 1
    - name: vm.swappiness
      value: 0

