---
- name: ミドルウェアをインストール
  yum: name={{item}} state=present
  with_items:
    - hadoop-hdfs-datanode
    - hadoop-lzo
    - hadoop-yarn-nodemanager
    - hadoop-mapreduce

# ライブラリの調整
- name: すでにあるslf4j-log4j12.jarを削除
  file:
    path: /usr/lib/hadoop/lib/slf4j-log4j12.jar
    state: absent

- name: シンボリックリンクの作成
  include: create_link_slf4j-log4j12jar.yml

- name: 自動起動すると危険なのでchkconfigをoffに　
  service:
    name: "{{ item }}"
    enabled: off
  with_items:
    - hadoop-hdfs-datanode
    - hadoop-yarn-nodemanager
