---
- name: cron,logrotate設定
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
  with_items: '{{ cron_info }}'

#dkvsmのみ
- name: 実行スクリプトを配置
  copy:
    src: dkvsm/{{ item }}
    dest: /etc/fsdkvs/bin/{{ item }}
    mode: '0755'
  with_items:
    - 'backup_log.sh'
    - 'restore.sh'
  when: "'dkvsm' in '{{ inventory_hostname }}'"

- name: backup_log crontabを設定
  cron:
    name: backup_log
    minute: "0"
    hour: "2"
    job: "/etc/fsdkvs/bin/backup_log.sh >/dev/null 2>&1"
  when: "'dkvsm' in '{{ inventory_hostname }}'"
# 何故backup.shは二つのサーバ動いていて、restoreは02でしか有効になっていないのか

- name: restore crontabを設定
  cron:
    name: restore
    minute: "25"
    hour: "2"
    weekday: "6-7"
    job: "/etc/fsdkvs/bin/restore.sh >/dev/null 2>&1"
  when: "'dkvsm02' in '{{ inventory_hostname }}'"
