---
- name: tomcatグループの作成
  group: 
    name: tomcat

- name: tomcatユーザの作成
  user:
    name: tomcat
    group: tomcat

- name: tomcatインストールディレクトリの作成
  file:
    state: directory
    path: '{{ item.path }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: '0755'
  with_items:
    - { path: /usr/local/tomcat , owner: tomcat, group: tomcat }
    - { path: /usr/local/tomcat/webapp, owner: tomcat, group: tomcat }
    - { path: /usr/local/tomcat7 , owner: tomcat, group: tomcat }
    - { path: /usr/local/tomcat7/webapp, owner: tomcat, group: tomcat }

- name: tomcatをインストール #エラーが発生した場合、yum installを行う
  yum:
    name: apache-tomcat

- name: tomcatのserver.xmlをコピー
  copy:
    src: server.xml
    dest: /usr/local/tomcat/conf/
    owner: tomcat
    group: tomcat
    mode: '0600'

- name: setenv.sh の設定
  copy:
    src: setenv.sh
    dest: /usr/local/tomcat/bin/setenv.sh
    owner: tomcat
    group: tomcat
    mode: '0755'

- name: tomcat/bin/のスクリプトファイル配置
  copy:
    src: tomcat_bin/{{ item }}
    dest: /usr/local/tomcat/bin/
    owner: tomcat
    group: tomcat
    mode: '0755'
  with_items:
    - startup.sh
    - shutdown.sh
    - setenv.sh
    - catalina.sh

- name: tomcat_logsのディレクトリを作成
  file:
    state: directory
    path: '{{ item }}'
    owner: tomcat
    group: tomcat
  with_items:
    - /usr/local/tomcat/logs
    - /usr/local/tomcat/webapps/tpas_api/ROOT

- name: tomcat起動に必要なディレクトリ作成
  file: 
    state: directory
    path: /usr/local/tomcat/webapps/tpas_api/ROOT
    owner: tomcat
    group: tomcat

- name: tomcat再起動
  become: tomcat
  command: /usr/local/tomcat/bin/startup.sh

- name: lvs_のシェルを配置
  copy:
    src: files/lvs/
    dest: /var/app/maintenance/bin/
    owner: tomcat
    group: tomcat
    mode: '0755'
  with_items:
    - lvs_add.sh
    - lvs_del.sh
