---

##Centos6.3
- name: copy repository for Centos6.3
  yum: name={{ item }} state=present enablerepo=fullspeed
  with_items:
    - kernel-firmware-2.6.32-279.22.1_1.el63.x86_64
    - kernel-2.6.32-279.22.1_1.el63.x86_64
  when: ansible_distribution_version == '6.3'
##Centos6.4
- name: copy repository for Centos6.4
  yum: name={{ item }} state=present enablerepo=fullspeed
  with_items:
    - kernel-firmware-2.6.32-358.23.2_1.el64.x86_64
    - kernel-2.6.32-358.23.2_1.el64.x86_64    
  when: ansible_distribution_version == '6.4'
##Centos6.5
- name: copy repository for Centos6.5
  yum: name={{ item }} state=present enablerepo=fullspeed
  with_items:
    - kernel-firmware-2.6.32-431.29.2_1.el65.x86_64
    - kernel-2.6.32-431.29.2_1.el65.x86_64  
  when: ansible_distribution_version == '6.5'
##Centos6.6
- name: copy repository for Centos6.6
  yum: name={{ item }} state=present enablerepo=fullspeed
  with_items:
    - kernel-firmware-2.6.32-504.30.3_1.el66.x86_64
    - kernel-2.6.32-504.30.3_1.el66.x86_64
  when: ansible_distribution_version == '6.6'

##Centos6.7
- name: copy repository for Centos6.7
  yum: name={{ item }} state=present enablerepo=fullspeed
  with_items:
    - kernel-firmware-2.6.32-573.7.1_1.el67.x86_64
    - kernel-2.6.32-573.7.1_1.el67.x86_64
    - kernel-2.6.32-573.7.1_1.el67.x86_64 kernel-firmware-2.6.32-573.7.1_1.el67.x86_64
  when: ansible_distribution_version == '6.7'

- name: copy
  copy: >
    src=kernel-firmware-2.6.32-642.1.1_1.el68.x86_64.rpm
    dest=/tmp/
  when: ansible_distribution_version == '6.7'

##Centos6.8
- name: copy repository for Centos6.8
  yum: name={{ item }} state=present enablerepo=fullspeed
  with_items:
    - kernel-2.6.32-642.1.1_1.el68.x86_64
  when: ansible_distribution_version == '6.8'

##install irqbalance
- name: install irqbalance
  yum: name=irqbalance state=present disablerepo=updates

##service irqbalance
- name: service
  service: name=irqbalance state=started

##multi-queue-network
- name: check1
  stat: path={{ tx0 }}
  register: fm
- name: aaa1
  shell: echo "echo "ffffffff" > /sys/class/net/em2/queues/tx-0/xps_cpus" >> /etc/rc.local
  when: fm.stat.exists

- name: check2
  stat: path={{ tx1 }}
  register: fm
- name: aaa2
  shell: echo "echo "ffffffff" > /sys/class/net/em2/queues/tx-1/xps_cpus" >> /etc/rc.local
  when: fm.stat.exists

- name: check3
  stat: path={{ tx2 }}
  register: fm
- name: aaa3
  shell: echo "echo "ffffffff" > /sys/class/net/em2/queues/tx-2/xps_cpus" >> /etc/rc.local
  when: fm.stat.exists

- name: check4
  stat: path={{ tx3 }}
  register: fm
- name: aaa4
  shell: echo "echo "ffffffff" > /sys/class/net/em2/queues/tx-3/xps_cpus" >> /etc/rc.local
  when: fm.stat.exists

- name: check5
  stat: path={{ tx4 }}
  register: fm
- name: aaa5
  shell: echo "echo "ffffffff" > /sys/class/net/em2/queues/tx-4/xps_cpus" >> /etc/rc.local
  when: fm.stat.exists

- name: check6
  stat: path={{ tx5 }}
  register: fm
- name: aaa6
  shell: echo "echo "ffffffff" > /sys/class/net/em2/queues/tx-5/xps_cpus" >> /etc/rc.local
  when: fm.stat.exists

- name: check7
  stat: path={{ tx6 }}
  register: fm
- name: aaa7
  shell: echo "echo "ffffffff" > /sys/class/net/em2/queues/tx-6/xps_cpus" >> /etc/rc.local
  when: fm.stat.exists

- name: check8
  stat: path={{ tx7 }}
  register: fm
- name: aaa8
  shell: echo "echo "ffffffff" > /sys/class/net/em2/queues/tx-7/xps_cpus" >> /etc/rc.local
  when: fm.stat.exists

- name: check9
  stat: path={{ tx8 }}
  register: fm
- name: aaa9
  shell: echo "echo "ffffffff" > /sys/class/net/em2/queues/tx-8/xps_cpus" >> /etc/rc.local
  when: fm.stat.exists



- name: check10
  stat: path={{ rx0 }}
  register: fm
- name: aaa10
  shell: echo "echo "ffffffff" > /sys/class/net/em2/queues/rx-0/rps_cpus" >> /etc/rc.local
  when: fm.stat.exists

- name: check11
  stat: path={{ rx1 }}
  register: fm
- name: aaa12
  shell: echo "echo "ffffffff" > /sys/class/net/em2/queues/rx-1/rps_cpus" >> /etc/rc.local
  when: fm.stat.exists

- name: check5
  stat: path={{ rx2 }}
  register: fm
- name: aaa5
  shell: echo "echo "ffffffff" > /sys/class/net/em2/queues/rx-2/rps_cpus" >> /etc/rc.local
  when: fm.stat.exists

- name: check6
  stat: path={{ rx3 }}
  register: fm
- name: aaa6
  shell: echo "echo "ffffffff" > /sys/class/net/em2/queues/rx-3/rps_cpus" >> /etc/rc.local
  when: fm.stat.exists

- name: check7
  stat: path={{ rx4 }}
  register: fm
- name: aaa7
  shell: echo "echo "ffffffff" > /sys/class/net/em2/queues/rx-4/rps_cpus" >> /etc/rc.local
  when: fm.stat.exists

- name: check8
  stat: path={{ rx5 }}
  register: fm
- name: aaa8
  shell: echo "echo "ffffffff" > /sys/class/net/em2/queues/rx-5/rps_cpus" >> /etc/rc.local
  when: fm.stat.exists

- name: check8
  stat: path={{ rx6 }}
  register: fm
- name: aaa8
  shell: echo "echo "ffffffff" > /sys/class/net/em2/queues/rx-6/rps_cpus" >> /etc/rc.local
  when: fm.stat.exists

- name: check8
  stat: path={{ rx7 }}
  register: fm
- name: aaa8
  shell: echo "echo "ffffffff" > /sys/class/net/em2/queues/rx-7/rps_cpus" >> /etc/rc.local
  when: fm.stat.exists

- name: check8
  stat: path={{ flow0 }}
  register: fm
- name: aaa8
  shell: echo "echo 4096 > /sys/class/net/em2/queues/rx-0/rps_flow_cnt" >> /etc/rc.local 
  when: fm.stat.exists

- name: check8
  stat: path={{ flow1 }}
  register: fm
- name: aaa8
  shell: echo "echo 4096 > /sys/class/net/em2/queues/rx-1/rps_flow_cnt" >> /etc/rc.local 
  when: fm.stat.exists

- name: check8
  stat: path={{ flow2 }}
  register: fm
- name: aaa8
  shell: echo "echo 4096 > /sys/class/net/em2/queues/rx-2/rps_flow_cnt" >> /etc/rc.local 
  when: fm.stat.exists

- name: check8
  stat: path={{ flow3 }}
  register: fm
- name: aaa8
  shell: echo "echo 4096 > /sys/class/net/em2/queues/rx-3/rps_flow_cnt" >> /etc/rc.local 
  when: fm.stat.exists

- name: check8
  stat: path={{ flow4 }}
  register: fm
- name: aaa8
  shell: echo "echo 4096 > /sys/class/net/em2/queues/rx-4/rps_flow_cnt" >> /etc/rc.local 
  when: fm.stat.exists

- name: check8
  stat: path={{ flow5 }}
  register: fm
- name: aaa8
  shell: echo "echo 4096 > /sys/class/net/em2/queues/rx-5/rps_flow_cnt" >> /etc/rc.local 
  when: fm.stat.exists

- name: check8
  stat: path={{ flow6 }}
  register: fm
- name: aaa8
  shell: echo "echo 4096 > /sys/class/net/em2/queues/rx-6/rps_flow_cnt" >> /etc/rc.local 
  when: fm.stat.exists

- name: check8
  stat: path={{ flow7 }}
  register: fm
- name: aaa8
  shell: echo "echo 4096 > /sys/class/net/em2/queues/rx-7/rps_flow_cnt" >> /etc/rc.local 
  when: fm.stat.exists

- name: check8
  stat: path={{ flow7 }}
  register: fm
- name: aaa8
  shell: echo "echo 4096 > /sys/class/net/em2/queues/rx-7/rps_flow_cnt" >> /etc/rc.local 
  when: fm.stat.exists

- name: check8
  stat: path={{ rps }}
  register: fm
- name: aaa8
  shell: echo "echo 32768 > /proc/sys/net/core/rps_sock_flow_entries" >> /etc/rc.local 
  when: fm.stat.exists

