---
- hosts: target
  become: yes
  vars_files:
    - vars/ssl_t-admatrix.jp.yml
  roles:
    - { role: ssl_t-admatrix.jp, tags: setting }

- hosts: target
  tasks:
    - name: apache再起動
      become: yes
      command: /etc/init.d/httpd restart
      tags: add
