---
- name: install yum-utils
  yum:
    name: yum-utils
    state: present

- name: add mysql57 repo
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el6-1.noarch.rpm
    state: present

- name: disable mysql80 repo
  command: yum-config-manager --disable mysql80-community > /dev/null

- name: enable mysql57 repo
  command: yum-config-manager --enable mysql57-community > /dev/null

- name: install mysql client
  yum:
    name: '{{ item }}'
  with_items:
    - mysql-community-client
    - mysql-community-server

# passwdをいつものに設定するまで
- name: start mysqld at first time
  service:
    name: mysqld
    state: started

- name: get the tmp password
  shell: cat /var/log/mysqld.log | grep "temporary password" | awk '{print $11}'
  register: tmp_pass

# 既存のパスワードを使えるようにルールを緩和
- name: change password validation to the easy way
  shell: |
    mysql -u root -p'{{ tmp_pass.stdout }}' --connect-expired-password -e "SET GLOBAL validate_password_length=4;"
    mysql -u root -p'{{ tmp_pass.stdout }}' --connect-expired-password -e "SET GLOBAL validate_password_policy=LOW;"

- name: change root user password
  shell: |
    mysql -u root -p'{{ tmp_pass.stdout }}' --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_passoword }}';"
