---
- name: バックアップを作成
  command: "cp {{ item }} {{ item }}.{{ date }}"
  with_items:
    - '{{ bidding_cer_path }}'
    - '{{ bidding_key_path }}'
    - '{{ data_cer_path }}'
    - '{{ data_key_path }}'
    - '{{ optout_cer_path }}'
    - '{{ optout_key_path }}'
    - /usr/local/apache2/conf/bidding-dsp.ad-m.asia/Domain_CA_SHA2.cer
    - /usr/local/apache2/conf/data-dsp.ad-m.asia/Domain_CA_SHA2.cer
    - /usr/local/apache2/conf/optout-dsp.ad-m.asia/Domain_CA_SHA2.cer
  ignore_errors: true

- name: ディレクトリがなければディレクトリを作成
  file:
    path: '{{ item }}'
    mode: 0755
    state: directory
  with_items:
    - /usr/local/apache2/conf/bidding-dsp.ad-m.asia
    - /usr/local/apache2/conf/data-dsp.ad-m.asia
    - /usr/local/apache2/conf/optout-dsp.ad-m.asia

- name: ファイルをコピー
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0755
  with_items:
    - { src: '{{ bidding_cer }}', dest: '{{ bidding_cer_path }}' }
    - { src: '{{ bidding_key }}', dest: '{{ bidding_key_path }}' }
    - { src: '{{ domain_ca_crt }}', dest: '{{ domain_ca_bidding_path }}' }
    - { src: '{{ data_cer }}', dest: '{{ data_cer_path }}' }
    - { src: '{{ data_key }}', dest: '{{ data_key_path }}' }
    - { src: '{{ domain_ca_crt }}', dest: '{{ domain_ca_data_path }}' }
    - { src: '{{ optout_cer }}', dest: '{{ optout_cer_path }}' }
    - { src: '{{ optout_key }}', dest: '{{ optout_key_path }}' }
    - { src: '{{ domain_ca_crt }}', dest: '{{ domain_ca_optout_path }}' }

- name: 設定ファイルのバックアップを作成
  command: cp /usr/local/apache2/conf/extra/httpd-ssl.conf /usr/local/apache2/conf/extra/httpd-ssl.conf.{{ date }}  

- name: 設定ファイルを一部書き換え(今回のみ)
  replace:
    path: /usr/local/apache2/conf/extra/httpd-ssl.conf
    regexp: 'Domain_CA_SHA2.cer'
    replace: 'JPRS_DVCA.cer'
#証明書の確認

- name: ssl証明書の確認
  shell: openssl x509 -text -noout -in '{{ bidding_cer_path }}'
  register: check_bidding_cer

- name: ssl証明書の確認
  command: openssl x509 -text -noout -in '{{ data_cer_path }}'
  register: check_data_cer

- name: ssl証明書の確認
  command: openssl x509 -text -noout -in '{{ optout_cer_path }}'
  register: check_optout_cer

- name: 鍵一致のテスト(bidding.cer)
  shell: openssl x509 -noout -modulus -in '{{ bidding_cer_path }}' | openssl md5
  register: match_bidding_cer

- name: 鍵一致のテスト(bidding.key)
  shell: openssl rsa -noout -modulus -in '{{ bidding_key_path }}' | openssl md5
  register: match_bidding_key

- name: 鍵一致のテスト(data.cer)
  shell: openssl x509 -noout -modulus -in '{{ data_cer_path }}' | openssl md5
  register: match_data_cer

- name: 鍵一致のテスト(data.key)
  shell: openssl rsa -noout -modulus -in '{{ data_key_path }}' | openssl md5
  register: match_data_key

- name: 鍵一致のテスト(optout.cer)
  shell: openssl x509 -noout -modulus -in '{{ optout_cer_path }}' | openssl md5
  register: match_optout_cer

- name: 鍵一致のテスト(optout.key)
  shell: openssl rsa -noout -modulus -in '{{ optout_key_path }}' | openssl md5
  register: match_optout_key

- name: apache設定ファイルの文法チェック
  command: /etc/init.d/httpd configtest
  register: configtest

- name: デバッグ)
  debug:
    var: check_bidding_cer.stdout_lines

- name: デバッグ
  debug:
    var: check_data_cer.stdout_lines

- name: デバッグ
  debug:
    var: check_optout_cer.stdout_lines

- name: デバッグ
  debug:
    var: match_bidding_cer.stdout_lines

- name: デバッグ
  debug:
    var: match_bidding_key.stdout_lines

- name: デバッグ
  debug:
    var: match_data_cer.stdout_lines

- name: デバッグ
  debug:
    var: match_data_key.stdout_lines

- name: デバッグ
  debug:
    var: match_optout_cer.stdout_lines

- name: デバッグ
  debug:
    var: match_optout_key.stdout_lines

- name: httpdのconfigtest
  debug:
    var: configtest.stderr

- name: apacheの起動
  command: /etc/init.d/httpd restart

- name: すぐにサービスインされないように10秒待つ
  pause:
    seconds: 10
