---
- name: date取得
  local_action: command date +"%Y%m%d"
  register: date

- name: fstabファイルのバックアップを取得
  become: ansible
  local_action: command rsync -av {{ inventory_hostname }}:/etc/fstab /home/ansible/common_build/roles/mount/files/{{ inventory_hostname }}_{{ date.stdout }}
  ignore_errors: yes

- name: 必要なライブラリをインストール
  yum:
    name: "{{ item }}"
  with_items:
    - nfs-utils
    - nfs-utils-lib
  when: "ansible_os_family == 'RedHat'"

- name: rpcプロセスを起動
  service:
    name: rpcbind
    state: started

- name: mount
  mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    state: mounted
    fstype: nfs
    opts: "{{ item.opts }}"
  with_items: "{{ mount_info }}"
  
- name: 権限設定
  file:
    path: "{{ item.path }}"
    mode: "0777"
  with_items: "{{ mount_info }}"
