---
- hosts: target
  become: yes
  tasks:
    - name: check tomcat version
      shell: /usr/local/tomcat/bin/version.sh
      register: tomcat_ver_result

    - name: tomcat version out
      debug: var=tomcat_ver_result.stdout_lines
