---
- hosts: target
  become: yes
  tasks:
    - name: check cpu name
      shell: grep "model name"  /proc/cpuinfo | head -1
      register: cpu_name_result

    - name: check cpu physical
      shell: grep physical.id /proc/cpuinfo | sort -u | wc -l
      register: cpu_physical_result

    - name: check cpu processor
      shell: grep processor /proc/cpuinfo | wc -l
      register: cpu_processor_result

    - name: cpu name out
      debug: var=cpu_name_result.stdout_lines

    - name: cpu physical out
      debug: var=cpu_physical_result.stdout_lines

    - name: cpu processor out
      debug: var=cpu_processor_result.stdout_lines
