---
- hosts: target
  become: yes
  tasks:
    - name: check ruby version
      shell: ruby --version
      register: ruby_ver_result

    - name: ruby version out
      debug: var=ruby_ver_result.stdout_lines
