---
- hosts: target
  become: yes
  tasks:
    - name: check nginx version
      shell: /usr/local/nginx/sbin/nginx -V 2>&1 | grep version
      register: nginx_ver_result

    - name: nginx version out
      debug: var=nginx_ver_result.stdout_lines
