---
- hosts: all
  become: true
  tasks:
    - name: RAID status check
      shell: /opt/dell/srvadmin/bin/omreport storage vdisk controller=0 | grep State
      register: raid_result
    - name: RAID result
      debug: var=raid_result.stdout

- hosts: all
  become: true
  tasks:
    - name: DISK status check
      shell: /opt/dell/srvadmin/bin/omreport storage pdisk controller=0 | grep State
      register: disk_result
    - name: DISK result
      debug: var=disk_result.stdout
