---
- hosts: target
  tasks:
    - name: lvsから外す
      command: mv /usr/local/nginx/html/health.html /usr/local/nginx/html/health.html_bk
      tags: remove

- hosts: target
  tasks:
    - name: lvsに戻す
      command: mv /usr/local/nginx/html/health.html_bk /usr/local/nginx/html/health.html
      tags: add
