- name: create azkaban directory
  file:
    path: /usr/local/src/azkaban-2.5.0
    mode: '0755'

- name: install azkaban-web-server
  unarchive:
    src: azkaban-web-server-2.5.0.tar.gz
    dest: /usr/local/src/azkaban-2.5.0/

- name: create symbolic link
  file:
    src: /usr/local/src/azkaban-2.5.0/azkaban-web-2.5.0/
    dest: /usr/local/azkaban
    state: link

- name: create directories
  file:
    path: '{{ item }}'
  with_items:
    - /usr/local/azkaban/tmp
    - /usr/local/azkaban/ssl
    - /usr/local/azkaban/pid
    - /usr/local/azkaban/logs

## keystoreだけ最後に手動でやらないといけないかも
#keytool -keystore keystore -alias jetty -genkey -keyalg RSA
#keytool -certreq -alias jetty -keystore keystore -file jetty.csr

- name: create azkaban directory
  file:
    path: /usr/local/src/azkaban/
    state: directory


- name: git clone azkaban repo
  unarchive:
    src: mysql-connector-java-5.1.28.tar.gz
    dest: /usr/local/src/

#エラーになるが、アプリ関連なので状況注視
- name: set mysql-connector-java
  command: /usr/local/src/mysql-connector-java-5.1.28/mysql-connector-java-5.1.28-bin.jar /usr/local/azkaban/extlib/

- name: copy config files
  template:
    src: azkaban.properties.j2
    dest: /usr/local/azkaban/conf/azkaban.properties

- name: copy global.properties
  copy:
    src: global.properties
    dest: /usr/local/azkaban/conf/global.properties

- name: copy azkaban-web-start.sh
  copy:
    src: azkaban-web-start.sh
    dest: /usr/local/azkaban/bin/

- name: copy azkaban-web-shutdown.sh
  copy: 
    src: azkaban-web-shutdown.sh
    dest: /usr/local/azkaban/bin/

#azkaban-executorの設定
- name: install azkaban-exector
  copy:
    src: azkaban-executor-server-2.5.0.tar.gz
    dest: /tmp

- name: copy azkaban-executor-start.sh
  copy:
    src: azkaban-executor-start.sh
    dest: /usr/local/azkaban/bin

- name: copy azkaban-executor-shutdown.sh
  copy:
    src: azkaban-executor-shutdown.sh
    dest: /usr/local/azkaban/bin

#azkaban-job-typeの設定
- name: install jobtypes
  unarchive:
    src: azkaban-jobtype-2.5.0-rc3.tar.gz
    dest: /usr/local/src

- name: create synbolic link
  file:
    src: /usr/local/src/azkaban-jobtype-2.5.0-rc3
    dest: /usr/local/azkaban/plugins/jobtypes

- name: copy commonprivate.properties
  copy:
    src: commonprivate.properties
    dest: /usr/local/azkaban/plugins/
