---
- name: sysctlを配置(batch02,05)
  copy:
    src: sysctl_for_02_05.yml
    dest: /etc/sysctl.conf
    mode: '0644'
  when: (inventory_hostname == 'batch02') or (inventory_hostname == 'batch05')

- name: create analysis directories
  file:
    path: /var/app/analysis
    mode: '0777'

- name: set sudo authority
  copy:
    src: sudoers_tomcat
    dest: /etc/sudoers.d/

- name: create analysis directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0777'
  with_items:
    - /var/app/analysis/summary/spot
    - /var/app/analysis/pid

- name: create webapp directory
  file:
    path: /usr/local/tomcat/webapps/mq-3pas.admatrix.jp
    owner: tomcat
    group: tomcat
    state: directory

#nasのマウント設定
- name: install nfs-utils
  yum:
    name: '{{ item }}'
  with_items:
    - nfs-utils
    - nfs-utils-lib

- name: start rpcbind
  command: /etc/rc.d/init.d/rpcbind start

- name: create mount points
  file:
    path: /{{ item }}
    state: directory
  with_items:
    - nas
    - nas/db
    - nas/cvpath
