---
- name: install jdk
  yum: name={{ item }} enablerepo=fullspeed
  with_items:
  - jdk1.8.0_77

- name: set jdk path
  lineinfile:
    dest=/etc/profile
    insertbefore='export PATH USER LOGNAME MAIL HOSTNAME HISTSIZE HISTCONTROL'
    line={{ item }}
  with_items:
    - 'PATH=$PATH:/usr/java/default/bin:/sbin'
