---
- name: static routeの設定
  win_route:
    destination: 172.18.0.0
    gateway: 172.17.1.20
    metric: 0
    state: present

- name: sysctl.confの値を修正
  sysctl:
    name: net.core.somaxconn
    value: 2048
    state: present

- name: set sudoers
  copy:
    src: sysops
    dest: /etc/sudoers.d/
