---
- name: copy scripts
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0755'
  with_items:
    - { src: ssh_cmd_main.sh, dest: /root/ssh_cmd_main.sh }
    - { src: lp_marklist.sh, dest: /root/lp_marklist.sh }

- name: set crontab
  cron:
    name: 'ssh_cmd_main.sh'
    minute: '01'
    hour: '15'
    job: '/bin/sh /root/ssh_cmd_main.sh >/dev/null 2>&1'

- name: set crontab
  cron:
    minte: '30'
    hour: '09'
    weekday: '1'
    job: 'LANG=ja_JP.UTF-8 /bin/sh /root/lp_marklist.sh >/dev/null 2>&1'

- name: create devops_cebu user
  user:
    name: devops_cebu

- name: set sudoers
  copy:
    src: sysops
    dest: /etc/sudoers.d/

##
- name: check to exist the id_rsa.pub
  stat:
    path: /root/.ssh/id_rsa.pub
  register: sshkey

- when: sshkey.stat.exists == false
  name: create a ssh key
  command: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''

- name: view ssh-key (copy here and paste to root@cal03:/root/.ssh/authorized_keys)
  command: cat /home/tomcat/.ssh/id_rsa.pub
