---
- hosts: target
  become: yes
  vars_files:
    - vars/ssl_optout-dsp.t-ad-m.asia.yml
  roles:
    - { role: ssl_optout-dsp.t-ad-m.asia, tags: setting }

- hosts: target
  tasks:
    - name: apache再起動
      become: yes
      command: /etc/init.d/httpd restart
      tags: add
