---
- hosts: target
  tasks:
    - name: lvsから外す
      command: mv /usr/local/apache2/htdocs/health.html /usr/local/apache2/htdocs/health.html_bk
      tags: remove

- hosts: target
  become: yes
  vars_files:
    - vars/ssl_bidding-dsp.ad-m.asia.yml
    - vars/ssl_data-dsp.ad-m.asia.yml
    - vars/ssl_optout-dsp.ad-m.asia.yml
  roles:
    - { role: ssl_bidding-dsp.ad-m.asia, tags: setting }
    - { role: ssl_data-dsp.ad-m.asia, tags: setting }
    - { role: ssl_optout-dsp.ad-m.asia, tags: setting }

- hosts: target
  tasks:
    - name: apache再起動
      become: yes
      command: /etc/init.d/httpd restart
      tags: add
      notify: lvsに戻す
    - name: 10秒待つ
      pause:
        seconds: 10
      tags: add
  handlers:
    - name: lvsに戻す
      command: mv /usr/local/apache2/htdocs/health.html_bk /usr/local/apache2/htdocs/health.html
