---
- hosts: add
  become: yes
  vars_files:
    - vars/nginx.yml
  roles:
    - ../common_build/roles/common_centos7
    - ../common_build/roles/java
    - ../common_build/roles/nginx_centos7
    - iapi
