---
- hosts: add
  become: yes
  vars_files:
    - vars/dbs03.yml
  roles:
    - ../common_build/roles/common
    - { role: mysql, tags: mysql }
    - { role: mysql_app_user, tags: mysql_app_user }
    - { role: ../common_build/roles/mount, tags: mount } 
    - { role: cron_dbsXX, tags: cron }

#以下/etc/sysctl.confの修正
#対象サーバがdbm or dbsの03, 04であれば以下の設定が必要
  tasks:
    - name: 03にてsysctl.confの一部削除
      sysctl:
        name: '{{ item.name }}'
        state: absent
      with_items:
        - { name: net.ipv4.tcp_fin_timeout }
        - { name: net.ipv4.tcp_max_tw_buckets }
        - { name: net.ipv4.tcp_max_syn_backlog }
        - { name: net.netfilter.nf_conntrack_max }
        - { name: net.nf_conntrack_max }
        - { name: net.core.somaxconn }
        - { name: net.core.netdev_max_backlog }
        - { name: net.ipv4.ip_local_port_range }
        - { name: net.ipv4.tcp_tw_reuse }
        - { name: net.core.rmem_max }
        - { name: net.core.wmem_max }
        - { name: net.ipv4.tcp_rmem }
        - { name: net.ipv4.tcp_wmem }
      when: "'03' in '{{ inventory_hostname }}'"

    - name: 04にて設定を削除
      sysctl:
        name: '{{ item.name }}'
        state: absent
      with_items:
        - { name: net.ipv6.conf.all.disable_ipv6 }
        - { name: net.ipv6.conf.default.disable_ipv6 }
        - { name: net.ipv6.conf.lo.disable_ipv6 }
        - { name: vm.swappiness }
        - { name: net.ipv4.tcp_fin_timeout }
        - { name: net.ipv4.tcp_max_tw_buckets }
        - { name: net.ipv4.tcp_max_syn_backlog }
        - { name: net.netfilter.nf_conntrack_max }
        - { name: net.nf_conntrack_max }
        - { name: net.core.somaxconn }
        - { name: net.core.netdev_max_backlog }
        - { name: net.ipv4.ip_local_port_range }
        - { name: net.ipv4.tcp_tw_reuse }
        - { name: net.core.rmem_max }
        - { name: net.core.wmem_max }
        - { name: net.ipv4.tcp_rmem }
        - { name: net.ipv4.tcp_wmem }
      when: "'04' in '{{ inventory_hostname }}'"
