---
- hosts: ansible 
  connection: local
  gather_facts: no
  roles:
    - { role: generate_ssh_keys}

- hosts: util
  roles:
      - { role: reporting_server }

- hosts: all:!ansible:!util
  roles:
      - { role: target_server }

- hosts: ansible
  connection: local
  gather_facts: no
  tasks:
    - name: Remove dynamically generated SSH keys
      file:
        path: /tmp/ssh
        state: absent
