---
- name: gccのインストール
  yum: 
    name: gcc
    state: present
    disablerepo: fullspeed    

- name: rubyファイルの展開
# あらかじめファイルをmanagementサーバに置いておく
  unarchive:
    src: ruby-2.0.0-p353.tar.gz
    dest: /usr/local/src

- name: configure実行
  command: ./usr/local/src/ruby-2.0.0-p353/configure

- name: makeコマンド実行
  make:
    chdir: /usr/local/src/ruby-2.0.0-p353
    target: install
    params:
      prefix: /usr/local/ruby-2.0.0/

- name: シンボリックリンクの設定
  file:
    state: link
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: '0777'
  with_items:
    - { src: /usr/local/ruby-2.0.0/, dest: /usr/local/ruby }
    - { src: /usr/local/ruby/bin/ruby, dest: /usr/bin/ruby }
