nginx_conf:
    - { src: ./roles/nginx/files/dadmin_02s/default.conf, dest: /etc/nginx/conf.d/, mode: '0644' }
    - { src: ./roles/nginx/files/dadmin_02s/nginx.conf, dest: /etc/nginx/, mode: '0644' }
