#!/bin/bash
#
# chkconfig: 2345 10 10 起動させるランレベル 起動時の優先度 停止時の優先度 の順番で設定
# description: datadog-agent. これはただの説明
 
case "$1" in
start)
    sudo start datadog-agent
    ;;
stop)
    sudo stop datadog-agent
    ;;
status)
    sudo status datadog-agent
    ;;
esac
