---
- name: create directory knowledgecs
  file:
    path: /var/local/tmp/knowledgecs
    state: directory
    mode: '0755'

- name: create directory monitoring
  file:
    path: /var/app/maintenance/monitoring
    state: directory
    mode: '0755'

- name: copy scripts
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: knowledgecs_get.sh, dest: /var/local/tmp/knowledgecs/knowledgecs_get.sh }
    - { src: error_log_size_check.sh, dest: /var/app/maintenance/monitoring/error_log_size_check.sh }

- name: set cron knowledgecs_get.sh
  cron:
    name: 'knowledgecs_get.sh'
    minute: '0'
    hour: '5'
    job: '/var/local/tmp/knowledgecs/knowledgecs_get.sh >/dev/null 2>&1'

- name: set cron error_log_size_check.sh
  cron:
    name: 'log error check datadog'
    minute: '*/10'
    job: '/var/app/maintenance/monitoring/error_log_size_check.sh >/dev/null 2>&1'

- name: set sudoers
  copy:
    src: sysops
    dest: /etc/sudoers.d/

- name: mysqlクライアントのインストール
  yum: name={{ item }}
  with_items:
    - mysql

- name: postfixのインストール
  yum: name={{ item }}
  with_items:
    - postfix
