---
- name: 本日の日付を取得
  local_action: command date +"%Y%m%d"
  register: date

- name: バックアップを作成
  command: "cp {{ item }} {{ item }}.{{ date.stdout }}"
  with_items:
    - '{{ crt_path }}'
    - '{{ key_path }}'
  ignore_errors: yes

- name: ファイルをコピー
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0755
  with_items:
    - { src: '{{ update_crt }}', dest: '{{ crt_path }}' }
    - { src: '{{ update_key }}', dest: '{{ key_path }}' }

- name: 鍵ファイルの権限変更
  file:
    path: '{{ key_path }}'
    mode: 0644

#debug
- name: ssl証明書の確認
  command: openssl x509 -text -noout -in '{{ crt_path }}'
  register: check_relay_crt

- name: 鍵の一致のテスト(relay.crt)
  shell: openssl x509 -noout -modulus -in '{{ crt_path }}' | openssl md5
  register: match_relay_crt

- name: 鍵の一致のテスト(relay.key)
  shell: openssl rsa -noout -modulus -in '{{ key_path }}' | openssl md5
  register: match_relay_key

- name: nginx設定ファイルの文法チェック
  command: /usr/local/nginx/sbin/nginx -t -c /etc/nginx/nginx.conf
  register: configtest

- name: debug
  debug: var=check_relay_crt.stdout_lines

- name: debug
  debug: var=match_relay_crt.stdout_lines

- name: debug
  debug: var=match_relay_key.stdout_lines

- name: debug
  debug: var=configtest.stderr_lines
