---
- name: Install python mysqldb module
  yum:
    name: MySQL-python

- name: Add DB users
  mysql_user:
    name: "{{ item.name }}"
    state: present
    password: "{{ item.password }}"
    host: "{{ item.host }}"
    priv: '*.*:select'
    login_user: root
    login_password: "{{ LOGIN_PASS }}"
  with_items: "{{ users_info }}"
