---
- name: install logrotate
  apt:
    name: logrotate
    update_cache: yes

- name: copy
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
  with_items: '{{ cron }}'

