---
- name: Register datadog.yaml stat
  stat:
    path: /etc/datadog-agent/datadog.yaml
  register: datadog_yaml

- name: Check if use_v2_api is in datadog.yaml
  when: datadog_yaml.stat.exists == True
  become: yes
  shell: "grep -A3 'use_v2_api' /etc/datadog-agent/datadog.yaml"
  register: v2_api
  ignore_errors: true

- name: Get the line numbers of all use_v2_api config set to true
  when: datadog_yaml.stat.exists == True and v2_api.stdout != '' 
  become: yes
  shell: "grep -A3 -n 'use_v2_api' /etc/datadog-agent/datadog.yaml | grep true | cut -f1 -d-"
  register: trueconfig_linenumber
  ignore_errors: true

- name: Update use_v2_api configs to false in datadog.yaml
  when: datadog_yaml.stat.exists == True and v2_api.stdout != ''
  become: yes
  command: "sed -i '{{ item }}s/true/false/g' /etc/datadog-agent/datadog.yaml"
  with_items: "{{ trueconfig_linenumber.stdout_lines }}"

- name: restart datadog-agent
  become: true
  service:
    name: datadog-agent
    state: restarted
    enabled: yes
