---
- hosts: add
  become: yes
  vars_files:
    - vars/nginx.yml
    - vars/mount.yml
  roles:
    - ../common_build/roles/common
    - ../common_build/roles/java
    - ../common_build/roles/nginx
    - relay
    - ssl_relay-dsp.ad-m.asia
    - ../common_build/roles/mount
