---
- hosts: target
  become: yes
  vars_files:
    - vars/ssl_relay-dsp.t-ad-m.asia.yml
  roles:
    - { role: ssl_relay-dsp.t-ad-m.asia, tags: setting }

- hosts: target
  tasks:
    - name: nginx再起動
      become: yes
      command: /usr/local/nginx/sbin/nginx -s reload
      tags: add
