---
- hosts: target
  tasks:
    - name: lvsから外す
      command: mv /usr/local/nginx/html/health.html /usr/local/nginx/html/health.html_bk
      tags: remove

- hosts: target
  become: yes
  vars:  #新しく配置する証明書を記載
    relay_crt: cn_relay-dsp.ad-m.asia_20180518.crt
    relay_key: relay-dsp.ad-m.asia_20180518.key
    date: "{{ lookup('pipe','date +%Y%m%d') }}"
  roles:
    - { role: ssl, tags: setting }

- hosts: target
  tasks:
    - name: apache再起動
      become: yes
      command: /usr/local/nginx/sbin/nginx -s reload
      tags: add
      notify: lvsに戻す
    - name: 10秒待つ
      pause:
        seconds: 10
      tags: add
  handlers:
    - name: lvsに戻す
      command: mv /usr/local/nginx/html/health.html_bk /usr/local/nginx/html/health.html
