-
  id: 1
  name: Yahoo
  domain: search.yahoo.co.jp,ws.mobile.yahoo.co.jp/bin/search
  parameter: p
-
  id: 2
  name: excite
  domain: .excite.co.jp
  parameter: q,word,k,keyword,kw,search,word
-
  id: 3
  name: bing
  domain: www.bing.com,m.bing.com
  parameter: q,key,keyword,search
-
  id: 4
  name: Google
  domain: .google.
  parameter: q,query,search/,/s/
  ad_keyword: aclk
-
  id: 5
  name: 楽天Infoseek
  domain: search.rakuten.co.jp,rakuten.co.jp/search,search.m.infoseek.co.jp/search,rakuten-search.naver.jp
  parameter: qt,q,kw
-
  id: 6
  name: BIGLOBE
  domain: .search.biglobe.ne.jp/,search.kbg.jp
  parameter: q,f_extrakey,MT,kw,keyword
-
  id: 7
  name: goo
  domain: .goo.ne.jp
  parameter: MT,kw,keyword,q,w,word,search_word
-
  id: 8
  name: nifty
  domain: .nifty.com
  parameter: Text,q,kw,key,word
-
  id: 9
  name: So-net
  domain: .so-net.ne.jp/search
  parameter: query,MT,kw,keyword
-
  id: 10
  name: ECナビ
  domain: .ecnavi.jp
  parameter: Keywords,keyword
-
  id: 11
  name: Ask
  domain: ask.com/web
  parameter: q
-
  id: 12
  name: JWord
  domain: search.jword.jp/
  parameter: name
-
  id: 13
  name: amazon
  domain: www.amazon.co.jp/s/
  parameter: field-keywords,keywords
-
  id: 14
  name: au
  domain: .auone.jp,ezsch.ezweb.ne.jp/search
  parameter: q,query,keyword
-
  id: 15
  name: ameba
  domain: .ameba.jp/search
  parameter: q,searchKey,keyword
-
  id: 16
  name: carview
  domain: search.carview.co.jp
  parameter: q
-
  id: 17
  name: fc2
  domain: search.fc2.com
  parameter: q
-
  id: 18
  name: BlogRanking
  domain: blog.with2.net/search
  parameter: q
-
  id: 19
  name: mixi
  domain: mixi.jp/search
  parameter: keyword
-
  id: 20
  name: AOL
  domain: search.aol.jp/aol/search
  parameter: query
-
  id: 21
  name: Hatena
  domain: www.hatena.ne.jp/o/search,search.hatena.ne.jp/search
  parameter: q,word
-
  id: 22
  name: AllAbout
  domain: search.allabout.co.jp/
  parameter: q
-
  id: 23
  name: livedoor
  domain: livedoor-search.naver.jp/search,dir.m.livedoor.com/search,.livedoor.com/search
  parameter: q,word,keyword
-
  id: 24
  name: 日本経済新聞
  domain: www.nikkei.com/search/
  parameter: searchKeyword
-
  id: 25
  name: OCN
  domain: wsearch.ocn.ne.jp/ocn
  parameter: MT
-
  id: 26
  name: Fresh
  domain: search.fresheye.com,fresheye.com/search
  parameter: kw,q
-
  id: 27
  name: 楽天
  domain: search.rakuten.co.jp/search/mall
  parameter: sitem
-
  id: 28
  name: ニワンゴ
  domain: niwango.jp/pc/search/,niwango.jp/mobile/*search/
  parameter: p1
-
  id: 29
  name: 魔法のiらんど
  domain: search.maho.jp
  parameter: q
-
  id: 30
  name: docomo
  domain: search.smt.docomo.ne.jp
  parameter: MT
-
  id: 31
  name: CNET
  domain: .cnet.com/search
  parameter: q
