---
- hosts: sweb #add the target inventory group
  become: yes
  tasks:
    - name: 設定ファイルの配布
      copy:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        mode: '{{ item.mode }}'
      with_items: '{{ nginx_conf }}'
