---
- name: Register mysql.d/conf.yaml stat
  stat:
    path: /etc/datadog-agent/conf.d/mysql.d/conf.yaml
  register: mysql_yaml

- name: Check if queries config is in mysql.d/conf.yaml
  when: mysql_yaml.stat.exists == True
  become: yes
  shell: "grep 'queries:' /etc/datadog-agent/conf.d/mysql.d/conf.yaml | cat"
  register: brandsafe_query
  ignore_errors: true
  
- name: Check if count from dsp.t_blackswan_response is in mysql.d/conf.yaml
  when: mysql_yaml.stat.exists == True and brandsafe_query.stdout != ''
  become: yes
  shell: "grep 'select count(\\*) as .* from dsp.t_blackswan_response' /etc/datadog-agent/conf.d/mysql.d/conf.yaml | cat"
  register: brandsafe_data
  ignore_errors: true

- name: Check if count from dsp.t_blackswan_candidate is in mysql.d/conf.yaml
  when: mysql_yaml.stat.exists == True and brandsafe_query.stdout != ''
  become: yes
  shell: "grep 'select count(\\*) as .* from dsp.t_blackswan_candidate' /etc/datadog-agent/conf.d/mysql.d/conf.yaml | cat"
  register: candidate_data
  ignore_errors: true
  
- name: Append the queries if mysql.d/conf.yaml exists but no queries yet
  when: mysql_yaml.stat.exists == True and brandsafe_query.stdout == ''
  become: yes
  blockinfile:
    path: /etc/datadog-agent/conf.d/mysql.d/conf.yaml
    block: |2
          queries:
            - query: select count(*) as brandsafe from dsp.t_blackswan_response
              metric: brandsafe.data.count
              type: gauge
              field: brandsafe
            - query: select count(*) as candidate from dsp.t_blackswan_candidate
              metric: candidate.data.count
              type: gauge
              field: candidate 
    marker: "# {mark} blackswan queries"

- name: Append "count t_blackswan_response" as query if mysql.d/conf.yaml exists
  when: mysql_yaml.stat.exists == True and brandsafe_query.stdout != '' and brandsafe_data.stdout == ''
  become: yes
  blockinfile:
    path: /etc/datadog-agent/conf.d/mysql.d/conf.yaml
    block: |3
              - query: select count(*) as brandsafe from dsp.t_blackswan_response
                metric: brandsafe.data.count
                type: gauge
                field: brandsafe
    marker: "# {mark} Brandsafe data count"

- name: Append "count t_blackswan_candidate" as query if mysql.d/conf.yaml exists
  when: mysql_yaml.stat.exists == True and brandsafe_query.stdout != '' and candidate_data.stdout == ''
  become: yes
  blockinfile:
    path: /etc/datadog-agent/conf.d/mysql.d/conf.yaml
    block: |3
              - query: select count(*) as candidate from dsp.t_blackswan_candidate
                metric: candidate.data.count
                type: gauge
                field: candidate 
    marker: "# {mark} Candidate data count"

- name: Copy conf.yaml to mysql.d/ if it does not exist yet
  when: mysql_yaml.stat.exists == False
  copy:
    src: conf.yaml
    dest: /etc/datadog-agent/conf.d/mysql.d/conf.yaml
    owner: dd-agent
    group: dd-agent
  become: true

- name: restart datadog-agent
  become: true
  service:
    name: datadog-agent
    state: restarted
    enabled: yes
