---
- name: 本日の日付を取得
  local_action: command date +"%Y%m%d"
  register: date

- name: バックアップを作成
  command: "cp {{ item }} {{ item }}.{{ date.stdout }}"
  with_items:
    - '{{ optout_crt_path }}'
    - '{{ optout_key_path }}'
    - '{{ optout_cer_path }}'
  ignore_errors: yes

- name: ファイルをコピー
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0755
  with_items:
    - { src: '{{ update_optout_crt }}', dest: '{{ optout_crt_path }}' }
    - { src: '{{ update_optout_key }}', dest: '{{ optout_key_path }}' }
    - { src: '{{ update_optout_cer }}', dest: '{{ optout_cer_path }}' }

- name: 鍵ファイルの権限変更
  file:
    path: '{{ optout_key_path }}'
    mode: 0644

#debug
- name: ssl証明書の確認
  command: openssl x509 -text -noout -in '{{ optout_crt_path }}'
  register: check_optout_crt

- name: 鍵の一致のテスト(cn_optout-dsp.ad-m.asia.cer)
  shell: openssl x509 -noout -modulus -in '{{ optout_crt_path }}' | openssl md5
  register: match_optout_crt

- name: 鍵の一致のテスト(optout-dsp.ad-m.asia.key)
  shell: openssl rsa -noout -modulus -in '{{ optout_key_path }}' | openssl md5
  register: match_optout_key

- name: apache設定ファイルの文法チェック
  command: /etc/init.d/httpd configtest
  register: configtest
  ignore_errors: yes

- name: debug
  debug: var=check_optout_crt.stdout_lines

- name: debug
  debug: var=match_optout_crt.stdout_lines

- name: debug
  debug: var=match_optout_key.stdout_lines

- name: debug
  debug: var=configtest.stderr_lines
