init_config:

instances:
  - server: 127.0.0.1
    user: datadog
    pass: 0ir6dpmpEqmu5gK8BkgSNBvG
    port: 3306
    queries:
      - query: select count(*) as brandsafe from dsp.t_blackswan_response
        metric: blackswan.brandsafe.data.count
        type: gauge
        field: brandsafe
      - query: select count(*) as candidate from dsp.t_blackswan_candidate
        metric: blackswan.candidate.data.count
        type: gauge
        field: candidate 