---
- hosts: add
  vars_files:
    - vars/ndmongom_cron.yml
  vars:
    host: ndmongom
  roles:
    - ../common_build/roles/common
    - mongodb2.6
    - cron
  tasks:
    - name: sysctl.confの値を一部削除
      sysctl:
        name: '{{ item.name }}'
        state: absent
      with_items:
        - net.ipv4.tcp_fin_timeout
        - net.ipv4.tcp_max_tw_buckets
        - net.ipv4.tcp_max_syn_backlog
        - net.netfilter.nf_conntrack_max
        - net.nf_conntrack_max
        - net.core.somaxconn
        - net.core.netdev_max_backlog
        - net.ipv4.ip_local_port_range
        - net.ipv4.tcp_tw_reuse
        - net.core.rmem_max
        - net.core.wmem_max
        - net.ipv4.tcp_rmem
        - net.ipv4.tcp_wmem
