---
- name: control onpremise server
  hosts: add
  become: true
  vars:
    gb_ip: 192.168.134.106 # global ipアドレス
    gb_interface: em2  # global ipを設定しているインターフェース名
  vars_files:
    - vars/nginx.yml
    - vars/mount.yml
  roles:
    - { role: ../common_build/roles/common } ##build tablet server
    - { role: ../common_build/roles/java }
    - { role: ../common_build/roles/tomcat }
    - { role: ../common_build/roles/ruby }
    - { role: api }
    - { role: ../common_build/roles/nginx }
    - { role: ../common_build/roles/mount }
    - { role: ../common_build/roles/hadoop_client }
  tasks:
    - name: sysctl.confの一部を修正
      sysctl:
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        state: '{{ item.state }}'
      with_items:
        - { name: net.ipv4.tcp_synack_retries, value: '3', state: present }
        - { name: net.netfilter.nf_conntrack_max, value: '500000', state: present}
        - { name: net.nf_conntrack_max, value: '500000', state: present }
        - { name: net.core.somaxconn, value: '2048', state: present }
        - { name: net.ipv4.conf.all.log_martians, value: '1', state: present }

    - name: sysctl.confの一部を削除
      sysctl:
        name: '{{ item.name }}'
        state: absent
      with_items:
        - { name: net.core.rmem_max }
        - { name: net.core.wmem_max }
        - { name: net.ipv4.tcp_rmem }
        - { name: net.ipv4.tcp_wmem }


    # 残作業として、apiサーバを追加した場合、batch01の/var/app/analysis/serverに
    # apiサーバのIPアドレスを追加する必要がある。（他のXapiサーバも同様）