---
- name: cloudera-cdh5リポジトリを設定
  copy:
    src: repos/{{item}}
    dest: /etc/yum.repos.d/
    mode: "0644"
  with_items:
    - cloudera-cdh5.repo
    - cloudera-gplextras5.repo

- name: hadoop-client周りをインストール
  yum: 
    name: '{{item}}'
    disablerepo: fullspeed
  with_items:
    - hadoop-client
    - hadoop-lzo
    - lzop

- name: hadoop-clientをインストール
  yum:
    name: hadoop-client

- name: conf.class/の設定ファイルを配置
  copy:
    src: '{{ item }}'
    dest: /etc/hadoop/conf.class/
    mode: '0644'
  with_fileglob:
    - ../files/conf.class/*
    
- name: conf.empty/を作成
  file:
    state: directory
    path: /etc/hadoop/conf.class/conf.empty
    mode: '0755'

- name: conf.empty/の設定ファイルを配置
  copy:
    src: '{{ item }}'
    dest: /etc/hadoop/conf.empty/
    mode: '0644'
  with_fileglob:
    - ../files/conf.empty/*

- name: conf.impala/の設定ファイルを配置
  copy:
    src: '{{ item }}'
    dest: /etc/hadoop/conf.impala/
    mode: '0644'
  with_fileglob:
    - ../files/conf.impala/*

- name: conf.distのシンボリックリンクを作成
  file:
    src: /etc/hadoop/conf.empty
    dest: /etc/hadoop/conf.dist
    state: link
    mode: '0777'

- name: /etc/hadoop/conf.classの有無をチェック
  stat:
    path: /etc/hadoop/conf.class
  register: conf_class

- name: /etc/hadoop/conf.empty/をコピーしてconf.class/作成
  shell: cp -r /etc/hadoop/conf.empty /etc/hadoop/conf.class
  when: conf_class.stat.exists == False

- name: hadoop/conf.classの標準コマンドを設定
  alternatives:
    name: hadoop-conf
    link: /etc/hadoop/conf
    path: /etc/hadoop/conf.class
    priority: "50"

- name: clients設定ファイルをコピー
  copy:
    src: '{{item}}'
    dest: /etc/alternatives/hadoop-conf
    mode: "0644"
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - mapred-site.xml

- name: hadoop-config.shのパラメータを修正。コメントアウト
  lineinfile:
    path: /usr/lib/hadoop/libexec/hadoop-config.sh
    regexp: '^JAVA_HEAP_MAX=-Xmx1000m'
    line: "#JAVA_HEAP_MAX=-Xmx1000m\nJAVA_HEAP_MAX=-Xmx3000m"

- name: インストール時にjavaが切り替わるのでoracleに戻す
  alternatives:
    name: java
    path: /usr/java/jdk1.8.0_77/jre/bin/java

- name: slf4j-log4j12-1.6.1.jarをコピー
  copy:
    src: slf4j-log4j12-1.6.1.jar
    dest: /usr/lib/zookeeper/lib/
    mode: "0644"

- name: シンボリックリンクを貼る
  file:
    src: /usr/lib/zookeeper/lib/slf4j-log4j12-1.6.1.jar
    path: /usr/lib/hadoop/lib/slf4j-log4j12.jar
    mode: "0777"
    state: link

- name: opensslインストール
  yum:
    name: openssl-devel
    disablerepo: fullspeed

- name: rubyインストール
  yum:
    name: ruby
    disablerepo: fullspeed

- name: dspユーザ作成
  user:
    name: dsp
    group: hadoop
