---
- hosts: add
  become: yes
  roles:
    - ../common_build/roles/common
  tasks:
    - name: sysctl.confの値を一部削除
      sysctl:
        name: '{{ item.name }}'
        state: absent
      with_items:
        - { name: net.ipv4.tcp_fin_timeout　}
        - { name: net.ipv4.tcp_max_tw_buckets }
        - { name: net.ipv4.tcp_max_syn_backlog }
        - { name: net.netfilter.nf_conntrack_max }
        - { name: net.netfilter.nf_conntrack_max }
        - { name: net.ipv4.ip_local_port_range }
    - name: sysctl.confの値を一部修正
      sysctl:
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        state: present
      with_items:
        - { name: net.nf_conntrack_max, value: '1000000' }
        - { name: net.core.somaxconn, value: '2048' }
        - { name: net.core.netdev_max_backlog, value: '2048' }
    - name: nginx用ディレクトリを作成
      file:
        state: directory
        path: /root/temp/work_pic
        mode: '0755'

- hosts: add
  become: yes
  vars_files:
    - vars/nginx.yml
    - vars/mount.yml
  roles:
    - ../common_build/roles/nginx
    - img
    - ../common_build/roles/mount
